version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Install sshpass
          command: sudo apt install sshpass
          
      - run: 
          name: Add sjump.comp.nus.edu.sg to known_hosts
          command: ssh-keyscan sjump.comp.nus.edu.sg >> ~/.ssh/known_hosts

      - run:
          name: SSH into cs1010s@stu.comp.nus.edu.sg
          command: sshpass -v -e ssh -o StrictHostKeyChecking=no -J muktar@sjump.comp.nus.edu.sg cs1010s@stu.comp.nus.edu.sg less deploy.sh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
